top_k: 3
max_jobs: 10
index_prefix: outputs/jobs_index
resume_path: templates/resume.tex
cover_path: templates/cover_letter.tex
personalize_model: claude-3-5-sonnet-latest
embed_model: sentence-transformers/all-MiniLM-L6-v2
personalized_dir: outputs/personalized

